apiVersion: apps/v1
kind: Deployment

metadata:
  name: rebustar-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: rebustar-api

  template:
    metadata:
      labels:
        app: rebustar-api

    spec:
      imagePullSecrets:
      - name: ghcr-secret

      containers:
      - name: rebustar-api
        image: ghcr.io/karthickkumarabs/rebustar-docker/rebustar-api:latest

        ports:
        - containerPort: 4015